const data = {
  products: [
    {
      id: 1,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "../images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 15,
    },
    {
      id: 2,
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "../images/p3.jpg",
      price: 90,
      brand: "Adidas",
      rating: 1.5,
      numReviews: 15,
      description: "high quality product",
      countInStock: 17,
    },
    {
      id: 3,
      name: "Nike Oversize Pants",
      category: "Pants",
      image: "../images/p4.jpg",
      price: 150,
      brand: "Nike",
      rating: 5,
      numReviews: 6,
      description: "high quality product",
      countInStock: 23,
    },
    {
      id: 4,
      name: "Adidas Slim Pants",
      category: "Pants",
      image: "../images/p5.jpg",
      price: 50,
      brand: "Adidas",
      rating: 4,
      numReviews: 20,
      description: "high quality product",
      countInStock: 51,
    },
    {
      id: 5,
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "../images/p3.jpg",
      price: 230,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 13,
      description: "high quality product",
      countInStock: 0,
    },
    {
      id: 6,
      name: "Lacoste Slim Jeans",
      category: "Pants",
      image: "../images/p4.jpg",
      price: 120,
      brand: "Lacoste",
      rating: 2.5,
      numReviews: 1,
      description: "high quality product",
      countInStock: 11,
    },
    {
      id: 7,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "../images/p1.jpg",
      price: 10,
      brand: "Nike",
      rating: 0,
      numReviews: 0,
      description: "high quality product",
      countInStock: 12,
    },
    {
      id: 8,
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "../images/p2.jpg",
      price: 39,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 12,
      description: "high quality product",
      countInStock: 0,
    },
  ],
};

export default data;
